//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/UserInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInputActions"",
    ""maps"": [
        {
            ""name"": ""UserActionMap"",
            ""id"": ""dd0b4ba3-8eeb-495f-8f7e-ab24b32c431a"",
            ""actions"": [
                {
                    ""name"": ""Pan"",
                    ""type"": ""Value"",
                    ""id"": ""12b7d7bc-3793-463a-827b-4e8600ee663b"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""6e42034c-c230-40f0-aa4c-5b6b2d03b633"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MainClick"",
                    ""type"": ""Button"",
                    ""id"": ""ccc491d5-6079-4fee-a6fd-fbff784cda62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""d3d6f319-7b53-418f-983d-2504bfe3194a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateGlobal"",
                    ""type"": ""Button"",
                    ""id"": ""d4ad3f5d-4ced-41bc-8f7e-d2154fee5f34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""5e7c03a3-26f3-4959-9e4f-5f87b579ed8a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""93bc1236-a9f8-4171-95c4-1c39307688f0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1041737a-f56b-4f6a-98c8-7901b8247106"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8b8cd0ff-3004-43e2-b84b-54b8d4ee534a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7670251d-3dba-4e98-bfac-0366b8f3acde"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""UpDownLeftRight"",
                    ""id"": ""a06fe1b1-8eef-46c3-944a-2006ad57fe6f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ffc13b42-5023-4465-b43a-9cdc41aec668"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ab550691-b36e-42a5-aa45-2bef048b937d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ff4ec7f5-9fd4-4604-b91c-bcfbb63eec8c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""76d41813-2805-42cf-b538-bb12869624d4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""60854eea-f7d2-4e98-b11a-7f5535598019"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""ccd1c239-c0ee-4528-8346-52622428f7a5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""3d670abd-a63f-4ff6-a79c-d311d9fb048c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7ba4ae1f-ca38-4ad2-bcea-370fb3e022a8"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11a84a78-38c9-4f9d-a8a8-3a0ed6bff1e5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6650317c-2585-4ec6-abc5-56ee681624c1"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""PageUpPageDown"",
                    ""id"": ""c7bc2ad3-b978-4c7b-bdc9-aa41f2bea00f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8ddddbaa-2977-43bc-88e8-5fa41dcdf725"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cd68682a-8246-4d00-ad77-9e8629b59a41"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MinusEquals"",
                    ""id"": ""44e9d574-5e18-499c-87ae-82b69d55acc6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8d0100f8-e891-4544-92b0-91155868ceb4"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3ace501a-ea36-4634-a5b7-07e0f0e6f7f9"",
                    ""path"": ""<Keyboard>/equals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UserActionMap
        m_UserActionMap = asset.FindActionMap("UserActionMap", throwIfNotFound: true);
        m_UserActionMap_Pan = m_UserActionMap.FindAction("Pan", throwIfNotFound: true);
        m_UserActionMap_Zoom = m_UserActionMap.FindAction("Zoom", throwIfNotFound: true);
        m_UserActionMap_MainClick = m_UserActionMap.FindAction("MainClick", throwIfNotFound: true);
        m_UserActionMap_PointerPosition = m_UserActionMap.FindAction("PointerPosition", throwIfNotFound: true);
        m_UserActionMap_RotateGlobal = m_UserActionMap.FindAction("RotateGlobal", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UserActionMap
    private readonly InputActionMap m_UserActionMap;
    private IUserActionMapActions m_UserActionMapActionsCallbackInterface;
    private readonly InputAction m_UserActionMap_Pan;
    private readonly InputAction m_UserActionMap_Zoom;
    private readonly InputAction m_UserActionMap_MainClick;
    private readonly InputAction m_UserActionMap_PointerPosition;
    private readonly InputAction m_UserActionMap_RotateGlobal;
    public struct UserActionMapActions
    {
        private @UserInputActions m_Wrapper;
        public UserActionMapActions(@UserInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pan => m_Wrapper.m_UserActionMap_Pan;
        public InputAction @Zoom => m_Wrapper.m_UserActionMap_Zoom;
        public InputAction @MainClick => m_Wrapper.m_UserActionMap_MainClick;
        public InputAction @PointerPosition => m_Wrapper.m_UserActionMap_PointerPosition;
        public InputAction @RotateGlobal => m_Wrapper.m_UserActionMap_RotateGlobal;
        public InputActionMap Get() { return m_Wrapper.m_UserActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IUserActionMapActions instance)
        {
            if (m_Wrapper.m_UserActionMapActionsCallbackInterface != null)
            {
                @Pan.started -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPan;
                @Pan.performed -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPan;
                @Pan.canceled -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPan;
                @Zoom.started -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnZoom;
                @MainClick.started -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnMainClick;
                @MainClick.performed -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnMainClick;
                @MainClick.canceled -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnMainClick;
                @PointerPosition.started -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPointerPosition;
                @PointerPosition.performed -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPointerPosition;
                @PointerPosition.canceled -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnPointerPosition;
                @RotateGlobal.started -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnRotateGlobal;
                @RotateGlobal.performed -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnRotateGlobal;
                @RotateGlobal.canceled -= m_Wrapper.m_UserActionMapActionsCallbackInterface.OnRotateGlobal;
            }
            m_Wrapper.m_UserActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pan.started += instance.OnPan;
                @Pan.performed += instance.OnPan;
                @Pan.canceled += instance.OnPan;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @MainClick.started += instance.OnMainClick;
                @MainClick.performed += instance.OnMainClick;
                @MainClick.canceled += instance.OnMainClick;
                @PointerPosition.started += instance.OnPointerPosition;
                @PointerPosition.performed += instance.OnPointerPosition;
                @PointerPosition.canceled += instance.OnPointerPosition;
                @RotateGlobal.started += instance.OnRotateGlobal;
                @RotateGlobal.performed += instance.OnRotateGlobal;
                @RotateGlobal.canceled += instance.OnRotateGlobal;
            }
        }
    }
    public UserActionMapActions @UserActionMap => new UserActionMapActions(this);
    public interface IUserActionMapActions
    {
        void OnPan(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnMainClick(InputAction.CallbackContext context);
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnRotateGlobal(InputAction.CallbackContext context);
    }
}
